### ISSUE TITLE
Crate support

### ISSUE THREAD

**Issue by martsokha** [sztomi/dap-rs#3]
Hi! I'm currently working on something like [jupyter-xeus/xeus](https://github.com/jupyter-xeus/xeus) but in Rust. 
I was wondering if I could count on `dap-rs` to enable DAP support.

**Comment by sztomi** [comment]
Hello, no sure what you are asking exactly?

**Comment by martsokha** [comment]
> Hello, no sure what you are asking exactly?

My question is whether there are plans to further develop this crate until it becomes stable.

**Comment by sztomi** [comment]
At the moment I'm not working on it actively because it's more or less feature-complete. It hasn't ever been used in a real project, so you will undoubtedly find bugs. If you report them, I'm happy to take a look and iron them out. I can't commit to anything though, this is a hobby project. I'm available for commercial support on a contracting basis if you have something like that in mind.
